const TRANSACTION_TYPE = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
  GENERAL: 'GENERAL',
}

const ACCOUNT_ADJUSTMENTS_CATEGORY = {
  value: 'Account Adjustments',
  transactionType: TRANSACTION_TYPE.GENERAL,
}

module.exports = {
  ACCOUNT_ADJUSTMENTS_CATEGORY,
  TRANSACTION_TYPE,
}
